name: Compiles only

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      id: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

    - name: add cr
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        wget -O $GITHUB_WORKSPACE/bin/cr http://repo.calcit-lang.org/binaries/linux/cr
        chmod +x $GITHUB_WORKSPACE/bin/cr
        echo "::add-path::$GITHUB_WORKSPACE/bin"

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac.git
        && git clone https://github.com/calcit-lang/memof.git
        && git clone https://github.com/calcit-lang/recollect.git
        && git clone https://github.com/Respo/respo.calcit.git
        && git clone https://github.com/Respo/respo-ui.calcit.git
        && git clone https://github.com/Respo/respo-message.calcit.git
        && git clone https://github.com/Cumulo/cumulo-util.calcit.git
        && git clone https://github.com/mvc-works/ws-edn.calcit.git

    - name: "compiles to js"
      run: yarn && yarn compile-page && yarn compile-server && yarn build-server && yarn vite build
