name: Compiles only

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      name: Cache node modules of yarn
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      id: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

    - name: add cr
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        wget -O $GITHUB_WORKSPACE/bin/cr http://repo.calcit-lang.org/binaries/linux/cr
        chmod +x $GITHUB_WORKSPACE/bin/cr
        echo "::add-path::$GITHUB_WORKSPACE/bin"

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac.git
        && git clone https://github.com/calcit-lang/memof.git
        && git clone https://github.com/calcit-lang/recollect.git
        && git clone https://github.com/Respo/respo.calcit.git
        && git clone https://github.com/Respo/respo-ui.calcit.git --branch 0.4.7
        && git clone https://github.com/Respo/respo-message.calcit.git
        && git clone https://github.com/Cumulo/cumulo-util.calcit.git
        && git clone https://github.com/mvc-works/ws-edn.calcit.git
        && git clone https://github.com/calcit-lang/calcit-wss.git
        && git clone https://github.com/calcit-lang/calcit.std.git

    - name: "compiles to js"
      run: yarn && cr --emit-js -1 && yarn vite build && cr --emit-ir -1 --entry server
